- name: Deploy WebServers
  hosts: WebServers
  roles:
    - app

- name: Deploy proxy servers
  hosts: Proxies
  roles:
    - nginx

- name: Deploy presentation converter
  hosts: Converter
  roles:
    - nodejs
