- name: Add NodeSource repository signing key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: Add NodeSource repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejs_version }} stretch main
    state: present
    filename: nodejs
- name: Install NodeJS
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
    update_cache: yes
