- name: Install Git used for clone application repository
  apt:
    name: "git"
    state: present
- name: Install ffmpeg repository keys
  apt:
    deb: http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
    state: present
- name: Add ffmpeg repository
  apt_repository:
    repo: deb http://www.deb-multimedia.org stretch main non-free
    state: present
    filename: ffmpeg

- name: Install ffmpeg
  apt:
    name: ffmpeg
    # default_release: stretch
    state: present

- name: Create user for NodeJS application
  user:
    name: rustv
    shell: "/sbin/nologin"
    create_home: no

- name: Clone application Git repository
  git:
    force: yes
    repo: "https://github.com/radoneje/rustv.git"
    dest: "{{ app_path }}"
  register: app_repo
  tags:
    - deploy-app

- name: Install dependencies
  npm:
    path: "{{ app_path }}"
  when: app_repo.changed
  tags:
    - deploy-app

- name: Deploy NodeJS app config for server {{ server_name.split()[0] }}
  template:
    src: "config.json.j2"
    dest: "{{ app_path }}/config.json"
  tags:
    - deploy-app

- name: Set NodeJS app directory owner
  file:
    dest: "{{ app_path }}"
    owner: "rustv"
    group: "rustv"
    recurse: yes
  tags:
    - deploy-app

- name: Deploy systemd startup script
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - "encoder.service"
    - "rustv.service"
  register: systemd
  tags:
    - deploy-app

- name: Start Node.JS applications
  systemd:
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
    state: restarted
  loop:
    - "encoder"
    - "rustv"
  tags:
    - deploy-app